Added corrected clause 138
ZaMaZaN4iK/holywar_laws pull request #3
Opened 2021-02-11 19:29 UTC by Kirundel

2021-02-11 19:41 UTC, urandon requested changes
It have to reformatted, it is not a correct multiline string.
@ZaMaZaN4iK can we add YAML linters to pull request CI checks?
We should try this https://github.com/marketplace/actions/yaml-lint

2021-02-11 19:41 UTC, urandon commented on holywar_rules.yaml
> +    text: Фурри и фуррифилы ограничены в правах. Их единственным правом является получение наказаний согласно ТКЧХ.
```suggestion
    text: >
        Фурри и фуррифилы ограничены в правах. Их единственным
        правом является получение наказаний согласно ТКЧХ.
```

2021-02-11 19:41 UTC, urandon commented on holywar_rules.yaml
> +          Прим. 1. Данная редакция статьи не подлежит исправлению по запросу фуррей и фуррифилов.
```suggestion
        Прим. 1. Данная редакция статьи не подлежит исправлению
        по запросу фуррей и фуррифилов. 
```

2021-02-12 08:59 UTC, ZaMaZaN4iK commented
> It have to reformatted, it is not a correct multiline string.
> @ZaMaZaN4iK can we add YAML linters to pull request CI checks?
> We should try this https://github.com/marketplace/actions/yaml-lint

I like the idea! Please make another PR for CI

2021-02-12 09:12 UTC, urandon approved these changes
Great contribution! 👍🏻

2021-02-12 09:24 UTC, urandon commented
> > It have to reformatted, it is not a correct multiline string.
> > @ZaMaZaN4iK can we add YAML linters to pull request CI checks?
> > We should try this https://github.com/marketplace/actions/yaml-lint
> 
> I like the idea! Please make another PR for CI

Great! Please, look at #4

2021-02-12 14:50 UTC, ZaMaZaN4iK commented
Please resolve conflicts and fix formatting, if necessary

2021-02-12 17:27 UTC, Periecle approved these changes
Good job, @Kirundel!

2021-02-12 17:35 UTC, ZaMaZaN4iK commented
Thanks!

2021-02-12 17:35 UTC, merged